### ISSUE TITLE
Query Exception

### ISSUE THREAD

**Issue by suwuzaa** [wi-wissen/InstaHub#2]
I installed evrything like described in https://github.com/wi-wissen/instahub

But when running php artisan migrate I get:

 Illuminate\Database\QueryException  : could not find driver (SQL: select * from information_schema.tables where table_schema = instahub and table_name = migrations

What can I do?

**Comment by wi-wissen** [comment]
Are you sure you have configured the database correctly as in 5? The error looks like PHP can't talk to MySQL.

Please excuse the late reply. I have not received any notification from GitHub.
