### ISSUE TITLE
Suche generiert falsches SQL-Statement bei Timestamp

### ISSUE THREAD

**Issue by RobbyBer** [wi-wissen/InstaHub#3]
Hallo,

beim Nutzen der Suchen gibt es ein Problem mit der Datumssuche. Wird z.B. beim Geburtsdatum ein Wert eingetragen werden im SQL-Statement keine Anführungszeichen eingefügt.
Wird am Anfang manuell ein Anführungszeichen eingefügt werden in der SQL Anfrage zwei öffnende und ein schließendes Anführungsziechen eingefügt.

![Auswahl_096](https://user-images.githubusercontent.com/45061486/64059797-785e0680-cbc3-11e9-8c83-b9297259e2ee.png)

![Auswahl_097](https://user-images.githubusercontent.com/45061486/64059815-afccb300-cbc3-11e9-8b83-4789395ffe42.png)

**Comment by wi-wissen** [comment]
Ich habe das Erkennen von Zahlen verbessert. Das englische Datumsformat wird nun korrekt als keine Zahl erkannt. Auch wird das Komma ersetzt durch einen englischen Punkt, wenn er innerhalb einer Zahl verwendet wird. Damit sollte es für die Mehrzahl aller Schüler*innen einfacher sein.

GitHub benachrichtigt nicht über Issues (oder ich finde es nicht), daher bitte ich die späte Antwort zu entschuldigen.
