### ISSUE TITLE
Feature request: provide "diverse" as additional gender

### ISSUE THREAD

**Issue by thoschneider** [wi-wissen/InstaHub#35]
Hi,
my students suggested a third gender "diverse" along with male and female in the registration form. I think they would be really happy and astonished to see this happening as I introduced them to github this week :) I know time is precious though.

**Comment by wi-wissen** [comment]
Solved: https://github.com/wi-wissen/InstaHub/commit/8dcffc6be1338c6e1f15a679190db85a972a87f5
