### ISSUE TITLE
Feature Request: Provide docker-based installation

### ISSUE THREAD

**Issue by pintman** [wi-wissen/InstaHub#4]
It would be great to have a dockerized version to install the tool on a server.

Maybe the following snippet can be used for first steps in this direction - if desired.

```
FROM debian:buster

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y composer php php-xml

WORKDIR /
RUN git clone git://github.com/wi-wissen/instahub.git

RUN apt-get install -y php-xml
WORKDIR /instahub
RUN composer install
```

**Comment by wi-wissen** [comment]
That's a good idea. Unfortunately, I don't have much experience with Docker. But I would be happy to accept a push request from you.

**Comment by mathiask** [comment]
I tried to make this work: see https://github.com/mathiask/InstaHub/tree/docker

I run it on GCP. To run it the following steps are needed:
- Check out the relevant branch
- bash docker/build.sh
the 'x' bit is not enough on GCP as the file system is mounted 'noexec'. This command builds two docker containers based on MySQL and php-apache, respectively.
- bash docker/run.sh

Now, you should be able to reach the server at instahub.test. You have to set up DNS yourself, e.g. in /etc/hosts or c;/Windows/System32/drivers/etc/hosts. All sub-domains have to be entered also.
I plan to run a DNS server (e.g. dnsmasq) maybe also in a container to set this up properly, but I haven't got around to it, yet.

After creating the first user, you might have to make them admin as described in the main README, but it also seems to work without this.

I am not sure whether it is fully functional as I have no experience with Instahub. But at least it no longer throws any exceptions...

**Comment by wi-wissen** [comment]
You need a "admin" mostly in production.

.env
```
APP_ENV=production
```
In this scenario all new users in a hub and new teachers in instahub (which are also users) have to be aproved (activated) manually.

"admin"-users may also see all hubs and not only their own.

Prouction disables also https://github.com/barryvdh/laravel-debugbar. This is a speed and security improvment. So should always use this flag in a public enviroment

**Comment by wi-wissen** [comment]
Since it is not an issue but a Feauture Request, where nobody contributes anything anymore, I close this one.

Feel free to reopen it if anyone has a docker solution.

**Comment by pintman** [comment]
Wouldn't it be better to have open feature requests open? Or are they handled otherwhere?

**Comment by wi-wissen** [comment]
Feel free to reopen the feauture request if you are still working on it.
I cannot and will not implement it, so at my point of view closed is the right status. 
Otherwise, it will only give others false hope?

**Comment by pintman** [comment]
I dont't have time to work on the issue now. However if it is a desired feature request it should be open, otherwise it could be closed. Maybe this issue could be a good start for an #hacktoberfest issue.
