### ISSUE TITLE
Typo bei Werbekampagnen

### ISSUE THREAD

**Issue by wunderlich** [wi-wissen/InstaHub#40]
Ich wurde gerade auf einen Typo im Formular für die Werbekampagnen hingewiesen. Leider kann ich die entsprechende Stelle im Quelltext auf die schnelle nicht finden, deshalb nur so:
![grafik](https://user-images.githubusercontent.com/4471366/155722787-b1019a76-e2ce-49a6-aa2f-772000b850e8.png)

**Comment by wi-wissen** [comment]
Vielen Dank für den Hinweis. 🙂
Ist im Beta-Branch richtig. Dieser geht heute live.
