### ISSUE TITLE
German Translation Error

### ISSUE THREAD

**Issue by Blocky38** [wi-wissen/InstaHub#42]
E-Mail Address instead of E-Mail Addresse in German translation on password reset.

I will try to submit an pull request for this later.

One question is this an project by a German speaking person? I have found an issue after logging in.

Greetings from Bavaria in Germany.

**Comment by wi-wissen** [comment]
Hey Blockly38,

I am from Leipzig and speak German.
Glad to hear that you try to submit a pull request. 👍
