### ISSUE TITLE
Size of Query Input

### ISSUE THREAD

**Issue by PhilippJust** [wi-wissen/InstaHub#72]
When creating or editing an ad campaign, the input for the SQL-Query is often too small to display the complete query.
I am thinking about replacing the `<input type=text...` by a `<textarea ...` 
What are your thoughts?

**Comment by wi-wissen** [comment]
Yes, this view definitely needs to be improved. A textarea is definitely a good step. As so often lacks time, but my dream is that this is also formatted with CodeMirror and you might even have a simulator that displays the result and checks for a link if that's where the ads would appear.

**Comment by wi-wissen** [comment]
Solved: https://github.com/wi-wissen/InstaHub/commit/8dcffc6be1338c6e1f15a679190db85a972a87f5
